n = input('Digite seu nome completo: ').strip()
print('Seu nome em maiúsculas é {}'.format(n.upper()))
print('Seu nome em minúsculas é {}'.format(n.lower()))
print('Seu nome tem ao todo {} letras'.format(len(n) - n.count(' ')))
dividido = n.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format((dividido[0]),len(dividido[0])))
