times = ('Internacional','Flamengo','Atlético-MG','Fluminense','São Paulo', 'Santos','Palmeiras','Grêmio','Sport','Fortaleza', 'Corinthians','Ceará','Atlético-GO','Botafogo','Bahia','Vasco','Coritiba','Bragantino','Athlético-PR','Goiás')
print('=' * 40)
print('Lista dos times do Brasileirão')
print('=' * 40)
print(times)
print('=' * 40)
print(f'Os cinco primeiros são: {times[0:5]}')
print('=' * 40)
print(f'Os 4 últimos são: {times[-4:]}')
print('=' * 40)
print('Times em ordem alfabética')
print(sorted(times))
print('=' * 40)
print(f'O time do Sport está na {times.index("Sport")+1}ª posição')
